default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: postgres
  password: test
  database: shorten_development
  host: localhost
test:
  <<: *default
  username: postgres
  password: test
  database: shorten_test
  host: localhost
production:
  <<: *default
  database: shorten_production
  username: shorten
  password: <%= ENV['SHORTEN_DATABASE_PASSWORD'] %>
